server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/gis_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
geocode.nominatim-base-urls=https://nominatim.openstreetmap.org,https://nominatim.openstreetmap.fr
geocode.user-agent=precision-observer-raster-api/1.0
geocode.connect-timeout-ms=3000
geocode.request-timeout-ms=8000
live.amap.key=f79686bdd30b832b10fc34b3fb9a4274
live.amap.geocode-url=https://restapi.amap.com/v3/geocode/geo
live.amap.district-url=https://restapi.amap.com/v3/config/district
live.stac.search-url=https://earth-search.aws.element84.com/v1/search
live.http-timeout-ms=12000
live.titiler.base-url=http://localhost:8000
live.titiler.tile-size=512
